CREATE DATABASE MY_DOCS
GO

USE MY_DOCS
GO

CREATE TABLE [USER](
	[ID] INT NOT NULL IDENTITY(1, 1),
	[NAME] VARCHAR(150) NOT NULL,
	[CPF] VARCHAR(14) NOT NULL,
	[DATE_OF_BIRTH] DATE NULL,
	[PHONE] VARCHAR(14) NULL,

	CONSTRAINT PK_USER PRIMARY KEY([ID])
);
GO

CREATE TABLE [USER_CREDENTIAL](
	[ID_USER] INT NOT NULL,
	[EMAIL] VARCHAR(200) NOT NULL,
	[PASSWORD] VARCHAR(14) NOT NULL,

	CONSTRAINT PK_USER_CREDENTIAL PRIMARY KEY([ID_USER]),
	CONSTRAINT FK_USER_USER_CREDENTIAL FOREIGN KEY([ID_USER]) REFERENCES [USER]([ID])
);

CREATE TABLE ALERT(
	[ID] INT NOT NULL IDENTITY(1, 1),
	[ID_USER] INT NOT NULL,
	[NAME] VARCHAR(70) NOT NULL,
	[DESCRIPTION] VARCHAR(200) NULL,
	[NR_RECURRENCE] INT NOT NULL,
	[CREATION_DATE] DATE NOT NULL,
	[END_DATE] DATE NULL,
	[CONFIGURATION] VARCHAR(MAX) NULL,

	CONSTRAINT PK_ALERT PRIMARY KEY([ID]),
	CONSTRAINT FK_ALERT_USER FOREIGN KEY([ID_USER]) REFERENCES [USER]([ID])
);

--CREATE TABLE LOG_ALERTS();

CREATE TABLE DOCUMENT(
	[ID] INT NOT NULL IDENTITY(1, 1),
	[ID_USER] INT NOT NULL,
	[FILE_NAME] VARCHAR(50) NOT NULL,
	[UNIQUE_FILE_NAME] VARCHAR(50) NOT NULL,
	[FILE_TYPE] VARCHAR(50) NOT NULL,
	[FILE_SIZE] BIGINT NOT NULL,
	[UPLOAD_DATE] DATE NOT NULL,

	CONSTRAINT PK_DOCUMENT PRIMARY KEY([ID]),
	CONSTRAINT FK_DOCUMENT_USER FOREIGN KEY([ID_USER]) REFERENCES [USER]([ID])
)

